namespace Entity {
  /// <summary>
  /// Represents class generated by Entity Framework
  /// This is the code analog to table structure of a table in a DB
  /// </summary>
  public class Horse {
    public int Id { get; set; }
    public string Name { get; set; }
    public int Legs { get; set; }
  }
}