using System.Collections.Generic;

namespace Enity {
  /// <summary>
  /// Represents class generated by Enity Framework
  /// </summary>
  public class Horse {
    public int Id { get; set; }
    public string Name { get; set; }
  }
}